### ISSUE TITLE
libceres.so not compile

### ISSUE THREAD

**Issue by tyutyuginslava** [hengli/camodocal#10]
Hi!

I get this error when compiling

This version is worth
http://faculty.cse.tamu.edu/davis/SuiteSparse/
SuiteSparse-3.7.1.tar.gz

Linking CXX shared library ../../../../lib/libceres.so
CMakeFiles/ceres.dir/covariance_impl.cc.o: In function `ceres::internal::CovarianceImpl::ComputeCovarianceValuesUsingSparseQR()':
/home/slava/workspace/camodocal/src/ceres-solver/internal/ceres/covariance_impl.cc:678: undefined reference to `long SuiteSparseQR<double>(int, double, long, cholmod_sparse_struct*, cholmod_sparse_struct**, long**, cholmod_common_struct*)'
collect2: error: ld returned 1 exit status

Help please!

**Comment by tyutyuginslava** [comment]
SuiteSparse which version are you using?

**Comment by hengli** [comment]
It looks like the SuiteSparseQR (libspqr.so) library is not compiled as part of SuiteSparse. Make sure that you do not have the system package libsuitesparse-dev installed (if you are using Ubuntu) as the system package does not include this library.

**Comment by ahundt** [comment]
Using a ceres-solver installed on the OS now works, so by following the [installation directions on the ceres-solver website](http://ceres-solver.org/building.html) things should work correctly. Feel free to reopen if problems persist.
