### ISSUE TITLE
 Unknown CMake command "camodocal_library".

### ISSUE THREAD

**Issue by Hu20130201** [hengli/camodocal#13]
Excuse me, shall I know anyone successfully build CamOdoCal with OpenCV 2.4.6 on Windows? There is a question below:
The C compiler identification is MSVC 16.0.30319.1
The CXX compiler identification is MSVC 16.0.30319.1
Check for working C compiler using: Visual Studio 10 2010
Check for working C compiler using: Visual Studio 10 2010 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 10 2010
Check for working CXX compiler using: Visual Studio 10 2010 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
CMake Error at brisk/CMakeLists.txt:12 (camodocal_library):
  Unknown CMake command "camodocal_library".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.0)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by ahundt** [comment]
camodocal_library is a cmake function defined within camodocal. perhaps it isn't being included? I don't have visual studio so I can't try it out myself.

**Comment by Hu20130201** [comment]
@athundt 
hi,
Assuming that I have the data(cameras(non-overlap),GPS/INS(Roll,Pitch,Yaw,Lat/Long)), I doubt whether I need run detector/descriptor! I mean whether I directly run the code?
Thank you very much

**Comment by ahundt** [comment]
Is this question related to the cmake question?

**Comment by ahundt** [comment]
I'm closing this issue, if problems persist please feel free to comment here or open a new issue.

**Comment by TrinhNC** [comment]
@Hu20130201 could you please tell me how you solved this problem?
