### ISSUE TITLE
Using Hand Eye Calibration

### ISSUE THREAD

**Issue by ahundt** [hengli/camodocal#17]
I'm trying to use the hand Eye calibration and I'm getting values that are way off, so I was hoping for some help. I'm using a robot arm and an optical tracker, aka camera, plus a fiducial attached to the end effector. In my case the camera is not on the hand, but instead sitting off to the side looking at the arm.

![HandEyeCalibrationQuestion](http://i.imgur.com/EPfPTky.png)

I'm moving the arm to a series of 36 points on a path (blue line), and near each point I'm taking a position (xyz) and orientation (angle axis with theta magnitude) of Camera->Fiducial and Base->EndEffector, and putting them in the vectors required by the [HandEyeCalibration Algorithm](https://github.com/hengli/camodocal/blob/master/include/camodocal/calib/HandEyeCalibration.h). I also make sure to vary the orientation by about +-30 degrees or so in roll pitch yaw.

I then run estimateHandEyeScrew, and I get the following results, and as you can see the position is off by an order of magnitude. 

[-0.0583, 0.0387, -0.0373] Real
[-0.185, -0.404, -0.59] Estimated with HandEyeCalib

Here is the full transforms and debug output:
```
# INFO: Before refinement: H_12 =
-0.443021 -0.223478  -0.86821  0.321341
 0.856051 -0.393099 -0.335633  0.470857
-0.266286 -0.891925   0.36546   2.07762
        0         0         0         1
Ceres Solver Report: Iterations: 140, Initial cost: 2.128370e+03, Final cost: 6.715033e+00, Termination: FUNCTION_TOLERANCE.
# INFO: After refinement: H_12 =
  0.896005   0.154992  -0.416117  -0.185496
 -0.436281    0.13281  -0.889955  -0.404254
-0.0826716   0.978948   0.186618  -0.590227
         0          0          0          1


expected RobotTipToFiducial (simulation only):   0.168   -0.861    0.481  -0.0583
expected RobotTipToFiducial (simulation only):   0.461   -0.362    -0.81   0.0387
expected RobotTipToFiducial (simulation only):   0.871    0.358    0.336  -0.0373
expected RobotTipToFiducial (simulation only):       0        0        0        1


estimated RobotTipToFiducial:   0.896    0.155   -0.416   -0.185
estimated RobotTipToFiducial:  -0.436    0.133    -0.89   -0.404
estimated RobotTipToFiducial: -0.0827    0.979    0.187    -0.59
estimated RobotTipToFiducial:       0        0        0        1

``` 

Am I perhaps using it in the wrong way? Is there any advice you can give?

**Comment by hengli** [comment]
HandEyeCalibration actually accepts relative motions as input, and not absolute poses. I think that is the main reason why it is not working.

**Comment by ahundt** [comment]
Oh thanks! I didn't realize that. So what you are saying is that each transform should be relative to an initial transform where I got the first frame, which I'll define as the base frame for the remaining transforms. Correct?

**Comment by hengli** [comment]
That's not true. Each transform should be relative to the immediate
previous transform. For example, we have the absolute poses T_ref_i of a
sensor for 0 <= i <= n. Here, we have n+1 poses, and T_ref_i is the
transformation that describes the pose of the sensor at time i with respect
to a fixed reference frame. The relative transform, T_(i-1)_i is defined to
be between T_ref_(i-1) and T_ref_i where T_(i-1)_i = T_ref_(i-1)^T * T_ref_i

**Comment by prclibo** [comment]
My interpretation: the T_(i - 1)_i or T_0_i can both be accepted. Actually any relative pose T_i_j can be used as input for the HandEyeCalibration.

This can be interpreted in this way: If you have the following equations suggested by @ahundt to solve the hand-eye calibration problem.
X^(-1) T_0_i X = S_0_i
X^(-1) T_0_(i - 1 X = S_0_(i - 1), (S is the pose of other object)

You can easily form the equations required by @hengli by eq1 dividing eq2 on both sides of the equator, so the two systems are equivalent, with only difference on numerical precision of the result.

**Comment by hengli** [comment]
@prclibo is actually correct. Sorry about my mistake. As @prclibo mentioned, we can use any relative pose.
