### ISSUE TITLE
Cata Camera calibration large gamma

### ISSUE THREAD

**Issue by inspirit** [hengli/camodocal#24]
Hello,

i was trying to calibrate the camera using Cata (MEI) model. how ever it results in very large 
gamma values (focal X/Y): 3000+
trying different models like Pinhole gives adequate focal values.
what can be the reason for such results?

**Comment by hengli** [comment]
Usually large gamma values come with large radial distortion values. I have noticed a strong positive correlation between gamma and radial distortion coefficients; I think that there is one redundant intrinsic calibration parameter. To remove the redundancy, we can set the first-order radial distortion parameter to 0, and keep it constant throughout.
