### ISSUE TITLE
Crash when running the examples/extrinsic_calib executable

### ISSUE THREAD

**Issue by xavkor** [hengli/camodocal#26]
When I run the example/extrinsic_calib executable, camodocal crashes during the optimization in beginStage 4. I use CUDA, OpenCV 2.4.9 on a Ubuntu 14.04 OS. Here's the console output:

./extrinsic_calib -v
(the exe runs well with about 200 images, then it stops suddenly )

Ceres Solver Report: Iterations: 100, Initial cost: 9.564510e+05, Final cost: 7.334577e+04, Termination: FUNCTION_TOLERANCE.
INFO: Done.
INFO: Reprojection error after BA (odometry): avg = 1.07 px | max = 30.75 px | # obs = 48068
INFO: # 3D scene points: 13924
INFO: Running robust pose graph optimization... 
INFO: Building odometry edges...
INFO: Built 222 odometry edges.
INFO: Building loop closure edges...
INFO: Built 0 loop closure edges.
Ceres Solver Report: Iterations: 0, Initial cost: 8.363728e-31, Final cost: 8.363728e-31, Termination: PARAMETER_TOLERANCE.
INFO: # inlier 2D-3D correspondences: 0
INFO: Merged 0 3D scene points.
INFO: Running BA on odometry data... 
INFO: Loss parameter = 25
INFO: sqrt precision matrix (keypoint position):
5 0
0 5
Ceres Solver Report: Iterations: 0, Initial cost: 7.322093e+04, Final cost: 7.322093e+04, Termination: FUNCTION_TOLERANCE.
INFO: Reprojection error after robust pose-graph optimization: avg = 1.07 px | max = 30.75 px | # obs = 48068
INFO: # 3D scene points: 13924
INFO: Finding inter-map 3D-3D correspondences... 
INFO: Entering frame set node 0-0 [ 1 ]
INFO: Entering frame set node 0-1 [ 2 ]
INFO: Entering frame set node 0-2 [ 3 ]
INFO: Entering frame set node 0-3 [ 4 ]
...
INFO: Entering frame set node 0-221 [ 7 ]
INFO: Entering frame set node 0-222 [ 7 ]
INFO: # local inter-map 3D-3D correspondences = 0
INFO: # features seen in camera 0: 0
INFO: Done.
INFO: Reprojection error after local matching: avg = 1.07 px | max = 30.75 px | # obs = 48068
INFO: # 3D scene points: 13924
INFO: Assigned weight of 0.00 to scene points observed by a single camera.
INFO: Running BA on odometry data -> optimize CAMERA_ODOMETRY_TRANSFORM | ODOMETRY_6D_POSE | POINT_3D ...
INFO: Added 222 residuals from odometry data.
INFO: Loss parameter = 25
INFO: sqrt precision matrix (keypoint position):
5 0
0 5
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0F0813 17043 46.173960: 43    :46.233960 1189111888  orrector.cc:42: Check failed: rho[1] > 0.0 (0 vs. 0)42] Check failed: rho[1] > 0.0 (0 vs. 0) F0813 17:43:46.233960 11892 corrector.cc:42] Check failed: rho[1] > 0.0 (0 vs. 0) F0813 17:43:46.233990 11893 corrector.cc:42] Check failed: rho[1] > 0.0 (0 vs. 0) F0813 17:43:46.233960 11895 corrector.cc:42] Check failed: rho[1] > 0.0 (0 vs. 0) F0813 17:43:46.233960 11896 corrector.cc:42] Check failed: rho[1] > 0.0 (0 vs. 0) 
*** Check failure stack trace: ***
F0F0813 17043 46.173960: 43    :46.233960 1189111888  orrector.cc:42: Check failed: rho[1] > 0.0 (0 vs. 0)42] Check failed: rho[1] > 0.0 (0 vs. 0) F0813 17:43:46.233960 11892 corrector.cc:42] Check failed: rho[1] > 0.0 (0 vs. 0) F0813 17:43:46.233990 11893 corrector.cc:42] Check failed: rho[1] > 0.0 (0 vs. 0) F0813 17:43:46.233960 11895 corrector.cc:42] Check failed: rho[1] > 0.0 (0 vs. 0) F0813 17:43:46.233960 11896 corrector.cc:42] Check failed: rho[1] > 0.0 (0 vs. 0) 
*** Check failure stack trace: ***
Abandon (core dumped)

I can't figure out why this failure appears. I searched for this error on google and I found this forum :https://groups.google.com/forum/#!topic/ceres-solver/kTMuM-6X3bo but this solution did'nt solved it. Do you have any idea why this problem appears?

**Comment by sandwichmaker** [comment]
This is interesting. Do you know what loss function is being used? and the values which trigger failure?

**Comment by hengli** [comment]
I see that only a single-camera system is being calibrated. I have not
tested this case before. The problem is that the weighting of all error
terms is 0 which is wrong. I have fixed this bug and committed the fix.
Please try running the code again.

**Comment by xavkor** [comment]
This bug doesn't appear anymore with the last commit. Thank you for the quick answer.
