### ISSUE TITLE
Possible cmake issue

### ISSUE THREAD

**Issue by stanathong** [hengli/camodocal#51]
@ahundt 

Referring to https://github.com/hengli/camodocal/issues/47

In comparison to the previous sourcecode, I found the latest sourcecode produced an error when running the command below:

cmake -DCMAKE_BUILD_TYPE=Release ..

The test environment is OpenCV 3.0 + No CUDA (on a virtual machine)

I attached logs in the post. Thanks very much.

[BuildCamOdocal_20150104.zip](https://github.com/hengli/camodocal/files/77256/BuildCamOdocal_20150104.zip)

**Comment by ahundt** [comment]
Was the package "Threads" found correctly in the cmake configure step?

Some possible similar workarounds:
https://stackoverflow.com/questions/29588183/cmake-fails-compilation
https://stackoverflow.com/questions/27567175/pthread-create-not-found-on-make-of-osrm-project

**Comment by stanathong** [comment]
@ahundt 

Thanks, Andrew. I will give this a try at a later time.

**Comment by ahundt** [comment]
Reopen if any problems related to this are still outstanding
