### ISSUE TITLE
Can't run extrinsic_calib

### ISSUE THREAD

**Issue by tancredosouza** [hengli/camodocal#63]
I've extracted the camera's intrinsic parameters using the first method. However, when I try to use the camera_chessboard_data.dat and camera_0_calib.yaml files to obtain the extrinsic parameters, it returns an error. 

To explain the folder hierarchy: the dataset folder inside _build_ has the (1) calib folder with the camera_0_calib.yaml file, the (2) calibration_data and (3) data used, respectively, for the output and 
the working data, and the (4) input folder, which contains the same .png chessboard images used for intrinsic calibration and parameters extraction, named camera_0_X.png.

Here is the command line I'm writing:
`bin/extrinsic_calib --calib /home/camodocal/build/dataset/calib --camera-count 1 --output /home/camodocal/build/dataset/calibration_data/ --input /home/camodocal/build/dataset/input --data /home/camodocal/build/dataset/data --event /home/camodocal/build/dataset/input/camera_chessboard_data.dat `

Here is the return:
`# INFO: Initializing... 
Read /home/camodocal/build/dataset/input/camera_chessboard_data.dat file to get all the events
# INFO: Initialization finished!
# INFO: Running camera-odometry calibration for each of the 1 cameras.
# ERROR: No segments, calibration fails!!
# INFO: Calibrating odometry - camera 0...
Rotation: 
 6.9117e-310 6.91165e-310  6.9117e-310
 6.9117e-310 6.91165e-310 7.90505e-323
6.91165e-310 6.91165e-310 6.91165e-310
Translation: 
2.52962e-321            0  6.9117e-310
# INFO: Completed camera-odometry calibration for all cameras.
# INFO: Saving intermediate data... Done. Took 0.00s.
# INFO: Running camera rig calibration.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0510 17:29:24.825707  4409 solver_impl.cc:354] Problem contains no parameter blocks.
Segmentation fault (core dumped)
`

Sorry if this is a very silly question, and thank you for your attention.

**Comment by blairlpp** [comment]
U have got the rotation and translation matrix which are matrices describing the relationship between the world coordinate and the camera coordinate. I have one question---What's the definition of the world coordinate here? @tancredosouza

**Comment by blairlpp** [comment]
Have u tried two or more cameras of a rig? @tancredosouza

**Comment by AmazingMei** [comment]
The same problem.

**Comment by cy-goh** [comment]
See [](https://github.com/hengli/camodocal/issues/91#issuecomment-698705828)
