### ISSUE TITLE
Bug found in cmake/LibraryConfig.cmake

### ISSUE THREAD

**Issue by nkwangyh** [hengli/camodocal#69]
In the `if(OpenCV_FOUND) ... endif()` part:
The three `if` branches following three `check_include_file_cxx` parts share the same structure as:
`if(have the file) ... 
elseif() print_error_message 
endif()`
These parts should be used to find the target files, if the files are not found, corresponding error messages will be printed out. But to print out the error message, `else()` instead of `elseif()` should be used. Since if `elseif()` is used, the printing part will be ignored when no target file was found.
So the `elseif()`s should be replaced with `else()`:
`if(have the file) ... 
else() print_error_message 
endif()`

**Comment by ahundt** [comment]
can you put this into a pull request so I can look at it more easily?

**Comment by nkwangyh** [comment]
Have created. But actually there is only a few changes. :-)
