### ISSUE TITLE
bin/extrinsic_calib Segmentation fault

### ISSUE THREAD

**Issue by sunjiayu12** [hengli/camodocal#74]
When I run: 
$ bin/extrinsic_calib --calib /home/miao/Desktop/camodocal/build/ --camera-count 1 --output /home/miao/Desktop/camodocal/build/calib --input /home/miao/Desktop/camodocal/data/newimage/ --data /home/miao/Desktop/camodocal/data/newimage/ --event /home/miao/Desktop/camodocal/build/camera_chessboard_data.dat 
in which --input contains *.bmp and frames*, --calib is generated by bin/intrinsic_calib, and --event is generated by bin/intrinsic_calib. 
However I got error like this: 
``` sh
# INFO: Initializing... 
Read /home/miao/Desktop/camodocal/build/camera_chessboard_data.dat file to get all the events
# INFO: Initialization finished!
# INFO: Running camera-odometry calibration for each of the 1 cameras.
# ERROR: No segments, calibration fails!!
# INFO: Calibrating odometry - camera 0...
Rotation: 
6.91456e-310 6.91452e-310 6.91456e-310
6.91456e-310 6.91452e-310 7.90505e-323
6.91452e-310 6.91452e-310 6.91452e-310
Translation: 
2.52962e-321            0 6.91456e-310
# INFO: Completed camera-odometry calibration for all cameras.
# INFO: Saving intermediate data... Done. Took 0.00s.
# INFO: Running camera rig calibration.
Segmentation fault (core dumped)
```
I wonder if the owner could give a dataset just for extrinsic_calib, thanks a lot. 
Anyone gives any suggestions is appreciated.

**Comment by AmazingMei** [comment]
I have the same problem

**Comment by AmazingMei** [comment]
@sunjiayu12 Have you solved the  problem?

**Comment by stillbreeze** [comment]
@sunjiayu12 @AmazingMei : Did any of you manage to solve this? I'm getting the same error.
```# ERROR: No segments, calibration fails!!```

**Comment by 1JIEZHAO** [comment]
@stillbreeze Can you run this program successfully? I have the same problem
"Segmentation fault"
