### ISSUE TITLE
intrinsic_calib not found in bin directory

### ISSUE THREAD

**Issue by abcd40404** [hengli/camodocal#81]
Hi,
I followed the step in readme, and I successfully built the code.
Then I tried to run example, but I can't find intrinsic_calib and stereo_calib exec file.
There are only dbow2_demo and train_voctree.
Did I miss anything?
Thanks.

**Comment by yuyadanyadan** [comment]
need to use the opencv > 3.0.0 with cuda and opencv_contrib

**Comment by abcd40404** [comment]
@yuyadanyadan  Thanks for reply, it works.

**Comment by TengFeiHan0** [comment]
@abcd40404  I got the same error and followed your instructions to install opencv_contrib,opencv and cuda. 
![Screenshot from 2019-08-07 17-02-26](https://user-images.githubusercontent.com/38068286/62609964-45fb1980-b935-11e9-93f4-cb65165359b0.png)




However, 
```
Looking for C++ include opencv2/face/facerec.hpp
-- Looking for C++ include opencv2/face/facerec.hpp - not found
-- OPENCV_CONTRIB NOT PRESENT, DISABLING LOTS OF FUNCTIONALITY, SEE https://github.com/opencv/opencv_contrib
-- Looking for C++ include opencv2/xfeatures2d/nonfree.hpp
-- Looking for C++ include opencv2/xfeatures2d/nonfree.hpp - not found
-- OPENCV_XFEATURES2D_NONFREE NOT PRESENT, DISABLING LOTS OF FUNCTIONALITY, SEE https://github.com/opencv/opencv_contrib
-- Looking for C++ include opencv2/cudafeatures2d.hpp
-- Looking for C++ include opencv2/cudafeatures2d.hpp - not found
-- OPENCV_CUDAFEATURES2D NOT PRESENT, DISABLING LOTS OF FUNCTIONALITY

```
these warnings still exist.  If possible, could you give me suggestions? @GUO-W @yuyadanyadan

**Comment by TrinhNC** [comment]
@TengFeiHan0 have you solved this problem?
