### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by pedropgusmao** [hengli/camodocal#93]
If you are getting Segmentation Fault caused by Eigen, remove 

> -march=native 

from CXX flags.

**Comment by debuleilei** [comment]
@pedropgusmao hello, I met the Segmentation fault problem, can you tell me where is the -march=native from the CXX flags…… thank you all the same

**Comment by m-tartari** [comment]
@debuleilei you can find them in [cmake/BuildConfigGCC.cmake](https://github.com/hengli/camodocal/blob/master/cmake/BuildConfigGCC.cmake).
